version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - python3.9 -m venv ~/.eb
      - source ~/.eb/bin/activate
      - make install
      - make lint
      - aws configure set region us-east-1

  build:
    commands:
      - make deploy